######################################################################
# Automatically generated by qmake (2.01a) Sat Jan 28 13:02:27 2012
######################################################################

TEMPLATE = subdirs

CONFIG += ordered

SUBDIRS = \
          data \
          util \
          dbcon \
          importer \
          gui \
          #
